backend:
  name: git-gateway
  branch: master

site_url: https://villav.gr
display_url: https://villav.gr
logo_url: https://villav.gr/static/logo-10ca3f6802601fe9401f81ff6097b14e.svg

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

media_library:
  name: uploadcare
  config:
    publicKey: 1f10af1508ea44bf53a6

collections:
#  - name: "blog"
#    label: "Blog"
#    folder: "src/pages/blog"
#    create: true
#    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
#    fields:
#      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
#      - {label: "Title", name: "title", widget: "string"}
#      - {label: "Publish Date", name: "date", widget: "datetime"}
#      - {label: "Description", name: "description", widget: "text"}
#      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
#      - {label: "Featured Image", name: "featuredimage", widget: image}
#      - {label: "Body", name: "body", widget: "markdown"}
#      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
#      - file: "src/pages/products/index.md"
#        label: "Products Page"
#        name: "products"
#        fields:
#          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
#          - {label: Title, name: title, widget: string}
#          - {label: Image, name: image, widget: image}
#          - {label: Heading, name: heading, widget: string}
#          - {label: Description, name: description, widget: string}
#          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
#          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
#          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
#          - {label: Full_image, name: full_image, widget: image}
#          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}

  - name: "spetses"
    label: "Spetses"
    preview_path: "spetses/{{slug}}"
    files:
      - file: "src/pages/spetses/index.md"
        label: "Spetses"
        name: "spetses"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/spetses/history/index.md"
        label: "History"
        name: "history"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/spetses/gettingaround/index.md"
        label: "Getting Around"
        name: "gettingaround"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/spetses/guide/index.md"
        label: "Travel Guide"
        name: "guide"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/spetses/events/index.md"
        label: "Events"
        name: "events"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/spetses/eating/index.md"
        label: "Eating"
        name: "eating"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/spetses/drinking/index.md"
        label: "Drinking and nightlife"
        name: "drinking"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
